### ISSUE TITLE
example project uses pulumi 2.0 when pulumi is  now 3

### ISSUE THREAD

**Issue by wlsidlsi** [pulumi/pulumi-component-provider-py-boilerplate#21]
### What happened?

Tried to run preview after following directions and got a random error.

`unhandled rejection: CONTEXT(15): transferDeps(resource:page[xyz:index:StaticPage], websiteUrl, undefined`

Tried going through the process of make generate, build, install several times thinking I missed a step because initially I was changing the name.  No luck.

I finally tried with the [pulumi-component-provider-ts-boilerplate](https://github.com/pulumi/pulumi-component-provider-ts-boilerplate) and it worked first time.

Looked at the package config and saw it was using  ^3.0.0 after checking my own version I am using the pulumi executable of later than 3 as well. 

Once I changed from 2 to 3 in the python repo no more errors.

May just be worth noting the readme next to Pulumi CLI to make sure the example package.json aligns with your installed Pulumi version as a fix.

### Steps to reproduce

Clone repo and follow steps in readme to preview example.

### Expected Behavior

```Previewing update (test):
     Type                          Name              Plan       
 +   pulumi:pulumi:Stack           simple-test       create     
 +   └─ puppy:index:StaticPage     ad                create     
 +      └─ aws:s3:Bucket           ad-bucket         create     
 +         ├─ aws:s3:BucketObject  ad-index-object   create     
 +         └─ aws:s3:BucketPolicy  ad-bucket-policy  create
```

### Actual Behavior

```
Previewing update (test):
     Type                 Name         Plan       Info
 +   pulumi:pulumi:Stack  simple-test  create     1 error; 143 messages```

  pulumi:pulumi:Stack (simple-test):
    unhandled rejection: CONTEXT(15): transferDeps(resource:page[xyz:index:StaticPage], websiteUrl, undefined)
    STACK_TRACE:
    Error:
```

### Output of `pulumi about`

```CLI          
Version      3.42.0
Go Version   go1.19.1
Go Compiler  gc

Host     
OS       darwin
Version  12.6
Arch     x86_64

Backend        
Name           MacBook-Pro.local
URL            file://~
User           commander_in_chief
Organizations
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by wlsidlsi** [comment]
My apologies if this shouldn't be tabled a bug.

**Comment by thomas11** [comment]
Speculatively opened #22

**Comment by wlsidlsi** [comment]
> To clarify, by package.json, do you mean [examples/simple/package.json](https://github.com/pulumi/pulumi-component-provider-py-boilerplate/tree/main/examples/simple)/package.json?

That is the correct package.json.  

> And which file do you mean by "the readme next to Pulumi CLI"?

Sorry that  did read terribly.  I just meant it may be easier to add a sidenote next to Pulumi CLI under requirements in the Readme similar to below.

# Prerequisites

- Pulumi CLI (in example, sdk version must match executable)
- Python 3.6+
- Node.js
- Yarn
Go 1.17
Node.js (to build the Node SDK)
.NET Code SDK (to build the .NET SDK)
